#!/bin/bash

case $1 in 

  ami) 
    AWS_PROFILE=test.builder packer build -var-file=infra/vm/variables.json infra/vm/packer.json
    ;;

   *)
            echo "Usage: $0 {ami}"
            exit 1
esac
