pre_tag="dev"
environment="development"
application_name="helloawsnode"
business_region="london"
instance_type="t2.micro"
aws_region="eu-west-2"

secondary_subnet="subnet-0d2b9940"
primary_subnet="subnet-35482e4e"
vpc_id="vpc-7ad7a313"
